### ISSUE TITLE
Cloud connection dropped on errors or slow response

### ISSUE THREAD

**Issue by ScruffR** [greiman/SdFat-Particle#1]
We are happy to have you on board and appreciate your work very much.
Just to prevent confusion for users, could you add a call to `Particle.process()` in places where your code may stay for more than 10sec, which would otherwise cause the cloud to drop?

e.g. `errorHalt()` features `while(1);` which prevents the Particle devices from being reflashed without Safe Mode. 
But with `while(1) Particle.process();` things would be fine.

Also in your demos you've got something like

``` cpp
  while (!Serial) { }  
  // or
  while (Serial.read() <= 0) { }
```

Where this would keep the cloud connection alive

``` cpp
  while (!Serial) Particle.process();
  // or
  while (Serial.read() <= 0) Particle.process();
```

Would be great if you could change that.

Thanks

**Comment by greiman** [comment]
I need to find a systematic solution.  SdFat is now used in many Arduino like systems and there are problems like this with each variation.

The bulk of the code is identical for each variation so I don't want a lot of separate versions of the code.  It may take a little while to settle on a general solution.

**Comment by ScruffR** [comment]
:+1:

**Comment by ScruffR** [comment]
I totally under

**Comment by ScruffR** [comment]
Sorry pressed the wrong button :blush: 

I totally understand, but how about something like

``` cpp
#if defined(SPARK)
#  define SDFAT_HANGAROUND Particle.process()
#else
#  define SDFAT_HANGAROUND
#endif

  while(!Serial) SDFAT_HANGAROUND;
```

Sure, it's not nice and `#define`s are evel, but ... you know ... :wink:

**Comment by greiman** [comment]
I need to address this and similar problems with a more general solution.

FatLib, the base library, is used for other devices like USB flash sticks and USB hard drives, not just SD cards.

The library is used in RTOS systems like ChibiOS, NilOS, FreeRTOS, and Arduino like systems for Arduino, Particle, ESP8266, STM32duino, and others.

My plan is to define a SysCall class with static member functions to wrap the calls I need for these boards/systems.

Particle.process() is sort of like yield() in many systems so I will do something like this.

```
while (!Serial) {
  SysCall::yield();
}
```

In the case of Particle, yield() will call Particle.process().

**Comment by greiman** [comment]
ScruffR,

I updated SdFat-Particle with mods that should fix most of the cloud connection drop problems.

I published the library and tried some of the examples.

**Comment by ScruffR** [comment]
:+1: 
I'll give it a try

Thanks
