### ISSUE TITLE
SdSpi.h: No such file or directory

### ISSUE THREAD

**Issue by SumanBD123** [greiman/SdFat-Particle#15]
Hi, 

I'm new to platform IO and Arduino. I am trying to compile code in platform IO it fails but the same project works in Arduino. 
I get the below error - 

`
            ^~~~~~~~~~~
In file included from src\ProteusBoard\SdFat\SdFat.h:26:0,
                 from src\ProteusBoard\SdFat\SdFatBase.cpp:20:
src\ProteusBoard\SdFat\SdSpiCard.h:29:10: fatal error: SdSpi.h: No such file or directory

***************************************************************
* Looking for SdSpi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:SdSpi.h"
* Web  > https://registry.platformio.org/search?q=header:SdSpi.h
*
*************************************************************** ` 

Help to solve is appreciated

**Comment by greiman** [comment]
I don't use platformIO.  Contact whoever installed SdFat on platformIO.

**Comment by greiman** [comment]
I has been many years since SdFatBase.cpp was part of SdFat.  src\ProteusBoard\SdFat must be very old.

**Comment by SumanBD123** [comment]
I totally agree it is a configuration error. 

Thanks for sharing such a useful library and your active support for the same.
