### ISSUE TITLE
SdFat, readbear duo, and arduino IDE

### ISSUE THREAD

**Issue by fakufaku** [greiman/SdFat-Particle#2]
Hi, I am trying to use the library with the redbear duo board and the arduino IDE. Is there a straightforward way to do that ?
At this point, some files are not found during compilation and the examples do not show up in the example menu.
Thanks in advance!
(Arduino IDE 1.6.7)

**Comment by greiman** [comment]
I don't have a redbear duo so I can't help you.

**Comment by fakufaku** [comment]
Thanks for the reply. How about with other boards ? Can you use your library with particle board and Arduino IDE 1.6.7 ?

**Comment by greiman** [comment]
In the past Particle didn't support the Arduino IDE.

**Comment by fakufaku** [comment]
Ok, thank you very much. I'll let you know if I am successful.

**Comment by mebarrington** [comment]
I found I had to put each example sketch in a folder inside the example folder and rename each example with ".ino" as the file extension.  Now the examples will show up in the Arduino IDE.

I am now having trouble getting them to compile. They are unable to find the header files associated with the sketches?
