### ISSUE TITLE
Libraries 2.0 upgrade

### ISSUE THREAD

**Issue by pkourany** [greiman/SdFat-Particle#5]
@greiman, can you please upgrade this (fantastic) library to the new Particle Libraries v2.0 format?  Thanks!

**Comment by greiman** [comment]
I will spend some time soon.  Probably I will just reformat it.

This library could use a major upgrade.  I have implemented a new library that supports exFat but have not decided how to publish it.

**Comment by pkourany** [comment]
@greimanm, lots of folks use SdFat and migrating to v2.0 libraries is easy, especially with Particle CLI.  A new library that supports exFat would be awesome as well!

**Comment by pkourany** [comment]
@greiman, FYI, it took all of 5 minutes to migrate the library to 2.0!  Use latest CLI, do `particle library migrate` from the repo folder and only the new properties files needs to be edited to include the `url` and `repository` entries.  You then upload and publish.  :)
