### ISSUE TITLE
Problem with Libraries 2.0

### ISSUE THREAD

**Issue by pkourany** [greiman/SdFat-Particle#6]
@greiman, it seems that the Particle IDE is having issues with the size of the library and I suspect it is due to the size of the documentation.  This prevents the library from actually loading in the IDE.   Anything you can do?

**Comment by greiman** [comment]
I guess I could delete the documentation.

I tested with the local particle-dev for atom.  It loaded SdFat with doc here:

C:\Users\bill\Documents\Particle\community\libraries\SdFat@0.0.5\doc

I don't use the IDE so I am lost.

I used good old make for my one serious particle project.

**Comment by pkourany** [comment]
@greiman, I tend to use CLI and local toolchain as well.  Any chance you can put the docs in a separate repo and just provide a link to it?  When you upload and publish your library to the IDE, I can test.

**Comment by greiman** [comment]
I think I fixed it.  I fumbled with the IDE and seems to get the new version, 0.0.6,  to load.

**Comment by pkourany** [comment]
@greiman, looks good so far.  I'll be testing later but thanks for your great work!
