### ISSUE TITLE
No matching function for call to 'SdFat::SdFat(int)'

### ISSUE THREAD

**Issue by Patrick-Thomas** [greiman/SdFat-Particle#8]
Fails to compile when selecting the alternate SPI configuration (on the Electron).
`
/workspace//src/podule.cpp:31:11: error: no matching function for call to 'SdFat::SdFat(int)'
 SYSTEM_THREAD(ENABLED);
           ^
/workspace//src/podule.cpp:31:11: note: candidates are:
In file included from /workspace//src/podule.cpp:13:0:
/workspace/lib/SdFat/src/SdFat.h:267:7: note: SdFat::SdFat()
 class SdFat : public SdFatBase {
       ^
/workspace/lib/SdFat/src/SdFat.h:267:7: note:   candidate expects 0 arguments, 1 provided
/workspace/lib/SdFat/src/SdFat.h:267:7: note: constexpr SdFat::SdFat(const SdFat&)
/workspace/lib/SdFat/src/SdFat.h:267:7: note:   no known conversion for argument 1 from 'int' to 'const SdFat&'
/workspace/lib/SdFat/src/SdFat.h:267:7: note: constexpr SdFat::SdFat(SdFat&&)
/workspace/lib/SdFat/src/SdFat.h:267:7: note:   no known conversion for argument 1 from 'int' to 'SdFat&&'
`

**Comment by greiman** [comment]
Can't help.  You don't provide code.

**Comment by Patrick-Thomas** [comment]
Managed to fix it. Turns out I hadn't selected one of my devices before compiling. Works fine now.
